name: K8s Chart Upgrade Test Matrix
run-name: Rancher `${{ inputs.rancher_version }}` upgrade to `${{ inputs.rancher_upgrade_version }}` on `${{ inputs.k3s_version }}` running `${{ inputs.tests_to_run }}` testing kubernetes `${{ inputs.k8s_upgrade_minor_version }}`

on:
  workflow_dispatch:
    inputs:
      rancher_version:
        description: Rancher version channel/version. This must be a released stable rancher version.
        required: true
        type: string
        default: latest/2.11.3
      rancher_upgrade_version:
        description: Rancher upgrade version
        required: true
        type: string
        default: head/2.12
      k8s_upgrade_minor_version:
        description: K8s minor version to test
        default: "1.33"
        required: true
        type: string
      k3s_version:
        description: k3s version of local cluster
        required: true
        type: string
        default: v1.32.1+k3s1
      qase_run_id:
        description: Qase run ID where the results will be reported (auto|none|existing_run_id)
        default: none
        type: string
      runner_template:
        description: Runner template to use
        default: hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v3
        type: string
      destroy_runner:
        description: Destroy the auto-generated self-hosted runner
        default: true
        type: boolean
      downstream_cluster_cleanup:
        description: Cleanup downstream clusters after test
        default: true
        type: boolean
      tests_to_run:
        description: Tests to run
        required: true
        default: k8s_chart_support_upgrade_provisioning/k8s_chart_support_upgrade_import
      providers:
        description: Providers to the run the test on
        required: true
        type: string
        default: '["eks", "gke", "aks"]'

jobs:
  e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        provider: ${{ fromJSON(inputs.providers) }}
    uses: ./.github/workflows/main.yaml
    secrets: inherit
    with:
      hosted_provider: ${{ matrix.provider }}
      rancher_version: ${{ inputs.rancher_version }}
      rancher_upgrade_version: ${{ inputs.rancher_upgrade_version }}
      k8s_upgrade_minor_version: ${{ inputs.k8s_upgrade_minor_version }}
      k3s_version: ${{ inputs.k3s_version }}
      tests_to_run: ${{ inputs.tests_to_run }}
      destroy_runner: ${{ inputs.destroy_runner }}
      runner_template: ${{ inputs.runner_template }}
      rancher_installed: 'hostname/password' # we pass hostname/password, but rancher will not be installed since NO_RANCHER_INSTALL will be set to true
      downstream_cluster_cleanup: ${{ inputs.downstream_cluster_cleanup }}
      operator_nightly_chart: false
      qase_run_id: ${{ inputs.qase_run_id }}
